#!/usr/bin/env python3
"""Generate an RC file that embeds every original game-data resource verbatim."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("resources", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    manifest = json.loads((args.resources / "manifest.json").read_text(encoding="utf-8"))
    root_from_output = Path("..") / args.resources
    lines = [
        "// Generated by tools/generate_resource_script.py; do not edit.",
        "// Numeric resource names/types intentionally mirror the original PE.",
        "",
    ]
    count = 0
    for item in manifest["resources"]:
        type_id = item["typeId"]
        if type_id is None or int(type_id) < 1000:
            continue
        name = str(item["name"])
        if not name.isdecimal():
            continue
        source = (root_from_output / str(item["path"])).as_posix()
        lines.append(f'{name} {type_id} "{source}"')
        count += 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"resources={count} output={args.output}")


if __name__ == "__main__":
    main()
