#pragma once

#define IDB_TITLE 101
#define IDB_CREDITS_BACKDROP 102

#define IDB_MENU_ONE_SELECTED 200
#define IDB_MENU_TWO_SELECTED 201
#define IDB_MENU_CONFIG_SELECTED 202
#define IDB_MENU_QUIT_SELECTED 203
#define IDB_MENU_ONE 210
#define IDB_MENU_TWO 211
#define IDB_MENU_CONFIG 212
#define IDB_MENU_QUIT 213
